#!/usr/bin/env bash
set -euo pipefail
set -x

COMMIT_WINDOW="${COMMIT_WINDOW:-2}"
ADAPTIVE_WINDOW="${ADAPTIVE_WINDOW:-2}"
TARO_ROOT="/root/autodl-tmp/taro"
VERL_ROOT="${TARO_ROOT}/verl"
MODEL_PATH="${TARO_ROOT}/models/Qwen3-1.7B"
TRAIN_FILE="${TARO_ROOT}/data/math/train.parquet"
VAL_FILE="${TARO_ROOT}/data/math/test.parquet"
REWARD_FILE="${VERL_ROOT}/taro_math_reward.py"
MAKESPAN_CSV="${TARO_ROOT}/analysis/taro_step1/makespan_v2_results.csv"

SEED="${SEED:-42}"
TOTAL_STEPS="${TOTAL_STEPS:-10}"
MAX_INFLIGHT="${MAX_INFLIGHT:-16}"
ACTIVATION_EPSILON="${ACTIVATION_EPSILON:-1e-6}"
RUN_NAME="${RUN_NAME:-qwen3_1.7b_taro_event_v2_seed${SEED}_${TOTAL_STEPS}steps}"
OUTPUT_ROOT="${TARO_ROOT}/outputs/taro_event/${RUN_NAME}"
ROLLOUT_DIR="${OUTPUT_ROOT}/rollouts"
VAL_OUTPUT_DIR="${OUTPUT_ROOT}/validation"
TARO_LOG_DIR="${OUTPUT_ROOT}/taro_trace"
CKPT_DIR="${TARO_ROOT}/checkpoints/${RUN_NAME}"
mkdir -p "${ROLLOUT_DIR}" "${VAL_OUTPUT_DIR}" "${TARO_LOG_DIR}" "${CKPT_DIR}"

export CUDA_VISIBLE_DEVICES=0
export CUDA_HOME=/usr/local/cuda-12.8
export PATH="${CUDA_HOME}/bin:${PATH}"
export LIBRARY_PATH="${CUDA_HOME}/targets/x86_64-linux/lib:${LIBRARY_PATH:-}"
export LD_LIBRARY_PATH="${CUDA_HOME}/targets/x86_64-linux/lib:${LD_LIBRARY_PATH:-}"
export TORCH_CUDA_ARCH_LIST="8.9"
export VLLM_USE_FLASHINFER_SAMPLER=0
export TOKENIZERS_PARALLELISM=true
export NCCL_DEBUG=WARN
export PYTHONPATH="${VERL_ROOT}:${PYTHONPATH:-}"

cd "${VERL_ROOT}"

python -m verl.trainer.main_ppo \
  --config-path=config \
  --config-name=ppo_megatron_trainer.yaml \
  algorithm.adv_estimator=grpo \
  algorithm.use_kl_in_reward=False \
  algorithm.kl_ctrl.kl_coef=0.0 \
  data.train_files="${TRAIN_FILE}" \
  data.val_files="${VAL_FILE}" \
  +data.apply_chat_template_kwargs.enable_thinking=True \
  data.train_batch_size=4 \
  data.train_max_samples=-1 \
  data.val_max_samples=128 \
  data.dataloader_num_workers=0 \
  data.max_prompt_length=512 \
  data.max_response_length=8192 \
  data.filter_overlong_prompts=True \
  data.truncation=error \
  data.shuffle=True \
  data.validation_shuffle=False \
  data.seed="${SEED}" \
  actor_rollout_ref.model.path="${MODEL_PATH}" \
  actor_rollout_ref.model.enable_gradient_checkpointing=False \
  actor_rollout_ref.model.use_remove_padding=True \
  actor_rollout_ref.model.use_fused_kernels=True \
  actor_rollout_ref.actor.optim.lr=1e-6 \
  +actor_rollout_ref.actor.optim.override_optimizer_config.optimizer_cpu_offload=True \
  +actor_rollout_ref.actor.optim.override_optimizer_config.optimizer_offload_fraction=1.0 \
  +actor_rollout_ref.actor.optim.override_optimizer_config.use_torch_optimizer_for_cpu_offload=False \
  +actor_rollout_ref.actor.optim.override_optimizer_config.overlap_cpu_optimizer_d2h_h2d=False \
  actor_rollout_ref.actor.ppo_mini_batch_size=2 \
  actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=2 \
  actor_rollout_ref.actor.ppo_epochs=1 \
  actor_rollout_ref.actor.use_dynamic_bsz=False \
  actor_rollout_ref.actor.ppo_max_token_len_per_gpu=8704 \
  actor_rollout_ref.actor.data_loader_seed="${SEED}" \
  actor_rollout_ref.actor.use_kl_loss=False \
  actor_rollout_ref.actor.entropy_coeff=0 \
  actor_rollout_ref.actor.use_fused_kernels=True \
  actor_rollout_ref.actor.use_torch_compile=False \
  actor_rollout_ref.actor.megatron.tensor_model_parallel_size=1 \
  actor_rollout_ref.actor.megatron.pipeline_model_parallel_size=1 \
  actor_rollout_ref.actor.megatron.context_parallel_size=1 \
  actor_rollout_ref.actor.megatron.sequence_parallel=False \
  actor_rollout_ref.actor.megatron.param_offload=False \
  actor_rollout_ref.actor.megatron.optimizer_offload=False \
  actor_rollout_ref.actor.megatron.grad_offload=False \
  actor_rollout_ref.actor.megatron.use_mbridge=True \
  actor_rollout_ref.actor.megatron.vanilla_mbridge=True \
  actor_rollout_ref.actor.megatron.dtype=bfloat16 \
  actor_rollout_ref.actor.megatron.use_remove_padding=True \
  actor_rollout_ref.actor.megatron.override_transformer_config.attention_backend=auto \
  actor_rollout_ref.actor.megatron.override_transformer_config.recompute_granularity=full \
  actor_rollout_ref.actor.megatron.override_transformer_config.recompute_method=uniform \
  actor_rollout_ref.actor.megatron.override_transformer_config.recompute_num_layers=1 \
  actor_rollout_ref.rollout.name=vllm \
  actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
  actor_rollout_ref.rollout.agent.num_workers=1 \
  +actor_rollout_ref.rollout.agent.agent_loop_manager_class=verl.experimental.agent_loop.taro_event_manager.TAROEventAgentLoopManager \
  actor_rollout_ref.rollout.checkpoint_engine.update_weights_bucket_megabytes=640 \
  actor_rollout_ref.rollout.gpu_memory_utilization=0.45 \
  actor_rollout_ref.rollout.max_model_len=8704 \
  actor_rollout_ref.rollout.max_num_batched_tokens=4096 \
  actor_rollout_ref.rollout.max_num_seqs=16 \
  'actor_rollout_ref.rollout.cudagraph_capture_sizes=[1,2,4,8,16]' \
  actor_rollout_ref.rollout.enable_chunked_prefill=True \
  actor_rollout_ref.rollout.free_cache_engine=True \
  actor_rollout_ref.rollout.enforce_eager=False \
  actor_rollout_ref.rollout.temperature=0.6 \
  actor_rollout_ref.rollout.top_p=0.95 \
  actor_rollout_ref.rollout.top_k=20 \
  actor_rollout_ref.rollout.n=1 \
  actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=2 \
  actor_rollout_ref.rollout.log_prob_use_dynamic_bsz=False \
  actor_rollout_ref.rollout.log_prob_max_token_len_per_gpu=8704 \
  actor_rollout_ref.rollout.val_kwargs.temperature=0.0 \
  actor_rollout_ref.rollout.val_kwargs.top_p=1.0 \
  actor_rollout_ref.rollout.val_kwargs.top_k=-1 \
  actor_rollout_ref.rollout.val_kwargs.n=1 \
  actor_rollout_ref.rollout.val_kwargs.do_sample=False \
  reward.custom_reward_function.path="${REWARD_FILE}" \
  reward.custom_reward_function.name=compute_score \
  reward.num_workers=1 \
  ++trainer.taro_online.enabled=true \
  ++trainer.taro_online.pilot_g=2 \
  ++trainer.taro_online.gmin=4 \
  ++trainer.taro_online.gmax=8 \
  ++trainer.taro_online.min_selected=3 \
  ++trainer.taro_online.activation_epsilon="${ACTIVATION_EPSILON}" \
  ++trainer.taro_online.total_budget=20 \
  ++trainer.taro_online.max_inflight="${MAX_INFLIGHT}" \
  ++trainer.taro_online.lambda_time=0.02 \
  ++trainer.taro_online.default_predicted_length=4096 \
  ++trainer.taro_online.seed="${SEED}" \
  ++trainer.taro_online.makespan_csv="${MAKESPAN_CSV}" \
  ++trainer.taro_online.log_dir="${TARO_LOG_DIR}" \
  ++trainer.taro_online.commit_window="$COMMIT_WINDOW" \
  ++trainer.taro_online.adaptive_window="$ADAPTIVE_WINDOW" \
  trainer.rollout_data_dir="${ROLLOUT_DIR}" \
  +trainer.validation_data_dir="${VAL_OUTPUT_DIR}" \
  trainer.log_val_generations=8 \
  trainer.project_name=taro \
  trainer.experiment_name="${RUN_NAME}" \
  'trainer.logger=["console"]' \
  trainer.n_gpus_per_node=1 \
  trainer.nnodes=1 \
  trainer.val_before_train=False \
  trainer.test_freq=-1 \
  trainer.save_freq=-1 \
  trainer.default_local_dir="${CKPT_DIR}" \
  trainer.resume_mode=auto \
  trainer.max_actor_ckpt_to_keep=2 \
  trainer.total_epochs=1 \
  trainer.total_training_steps="${TOTAL_STEPS}"
